fix(simulator): replace undefined currentAge with ageP1
Fixed ReferenceError where currentAge variable was used but not defined.
The correct variable ageP1 (defined at line 476) should be used instead.

Changes:
- Line 559: alterBeiErschoepfung[i] = currentAge -> ageP1
- Line 579: alterBeiErschoepfung[i] = currentAge -> ageP1

Fixes the error:
ReferenceError: currentAge is not defined at runMonteCarlo (simulator-main.js:559:51)